import { useMemo, useState } from "react";
import { expensePeriod, periodExpense } from "./calculations";
import { buildExpenseSeries } from "./chartData";
import { addDays, formatShortDate } from "./dateUtils";
import type { AppSettings, LifeRecord } from "./types";

export function VariableExpenseCard({ records, settings, today }: { records: LifeRecord[]; settings: AppSettings; today: string }) {
  const actualPeriod = useMemo(() => expensePeriod(today, settings.variableExpenseStartDay), [settings.variableExpenseStartDay, today]);
  const points = useMemo(() => buildExpenseSeries(records, actualPeriod, today), [records, actualPeriod, today]);
  const [selectedDate, setSelectedDate] = useState<string | null>(null);
  const selected = points.find((point) => point.date === selectedDate);
  const spent = periodExpense(records, actualPeriod);
  const remaining = settings.variableExpenseBudget - spent;
  const width = 640; const height = 190; const padding = { top: 12, right: 12, bottom: 32, left: 12 }; const plotWidth = width - padding.left - padding.right; const plotHeight = height - padding.top - padding.bottom; const step = plotWidth / Math.max(points.length, 1); const barWidth = Math.max(5, Math.min(18, step - 3)); const max = Math.max(1, ...points.map((point) => point.total ?? 0));
  return <section className="chart-card expense-chart-card"><div className="chart-card-head"><div><h2>今期の変動費</h2><p>{formatShortDate(actualPeriod.start)}〜{formatShortDate(actualPeriod.end)}</p></div><strong className={remaining < 0 ? "expense-over" : ""}>{remaining >= 0 ? `残り ${remaining.toLocaleString("ja-JP")}円` : `超過 ${Math.abs(remaining).toLocaleString("ja-JP")}円`}</strong></div><div className="expense-legend"><span className="everyday">日常</span><span className="satisfaction">満足</span><span className="regret">反省</span></div><div className="chart-wrap"><svg className="expense-chart" viewBox={`0 0 ${width} ${height}`} role="img" aria-label="今期の日別変動費"><rect className="sleep-chart-bg" width={width} height={height} rx="8" />{points.map((point, index) => { const x = padding.left + index * step + step / 2; const base = padding.top + plotHeight; const a = point.everyday / max * plotHeight; const b = point.satisfaction / max * plotHeight; const c = point.regret / max * plotHeight; return <g key={point.date}>{selectedDate === point.date && <rect className="sleep-col-highlight" x={x - step / 2} y={padding.top} width={step} height={plotHeight} />}<rect className="expense-bar-everyday" x={x - barWidth / 2} y={base - a} width={barWidth} height={a} rx="2" /><rect className="expense-bar-satisfaction" x={x - barWidth / 2} y={base - a - b} width={barWidth} height={b} rx="2" /><rect className="expense-bar-regret" x={x - barWidth / 2} y={base - a - b - c} width={barWidth} height={c} rx="2" />{(index === 0 || index === points.length - 1 || index % 5 === 0) && <text className="sleep-axis date" x={x} y={height - 10}>{formatShortDate(point.date)}</text>}<rect className="sleep-hit" x={x - step / 2} y={padding.top} width={step} height={plotHeight + padding.bottom - 4} onClick={() => setSelectedDate(selectedDate === point.date ? null : point.date)} /></g>; })}</svg></div>{selected && <div className="chart-detail"><strong>{formatShortDate(selected.date)}</strong><span>日常 {selected.total === null ? "-" : `${selected.everyday.toLocaleString("ja-JP")}円`}　満足 {selected.total === null ? "-" : `${selected.satisfaction.toLocaleString("ja-JP")}円`}　反省 {selected.total === null ? "-" : `${selected.regret.toLocaleString("ja-JP")}円`}　合計 {selected.total === null ? "-" : `${selected.total.toLocaleString("ja-JP")}円`}</span></div>}{points.every((point) => point.total === null) && <p className="empty">今期の変動費はまだ入力されていません。</p>}</section>;
}
